# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kappa Eta Kappa
email: webmaster@delta.khk.org
description: >- # this means to ignore newlines until "baseurl:"
  Kappa Eta Kappa is a national, professional co-ed Electrical
  Engineering Fraternity founded 1923. Delta Chapter is located
  at the University of Wisconsin, Madison.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://delta.khk.org" # the base hostname & protocol for your site, e.g. http://example.com
port: 1924
twitter_username: khkDelta
github_username: kappaetakappa

# Build settings
markdown: kramdown
future: true

collections:
  members:
    output: true
  events:
    output: true

defaults:
  -
    scope:
      path: ""
      type: members
    values:
      layout: "members_layout"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post_layout"
  -
    scope:
      path: ""
      type: events
    values:
      layout: "event_layout"

paginate: 3
paginate_path: /posts/page:num/

excerpt_separator: <!-- More -->

# The following items will not be processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - posts/README.md
  - _posts/README.md
  - events/README.md
  - _events/README.md
  - _members/README.md
